services:
  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "0.0.0.0:6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
