services:
  keycloak:
    container_name: keycloak
    # 国内镜像：docker.1ms.run/quay.io/keycloak/keycloak:26.2
    image: quay.io/keycloak/keycloak:26.2
    restart: unless-stopped
    command: start-dev
    ports:
      - "0.0.0.0:${KEYCLOAK_PORT}:8080"
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_HEALTH_ENABLED: "true"
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: localhost\r\n\r\n\" >&3;if [ $? -eq 0 ];then echo 'Health check successful';exit 0;else echo 'Health check failed';exit 1;fi"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s
