services:
  rustfs:
    container_name: rustfs
    image: ghcr.io/rustfs/rustfs:latest
    restart: unless-stopped
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      RUSTFS_WORKERS: "4"
      RUSTFS_MAX_UPLOAD_SIZE: "104857600"
      RUSTFS_ALLOWED_EXTENSIONS: ""
      RUSTFS_STORAGE_PATH: /data
      RUSTFS_PUBLIC_URL: http://172.16.0.1:8000
      RUSTFS_AUTH_TOKEN: ""
    volumes:
      - ./storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
